routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;
use App\Http\Controllers\Admin\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin'], function () {
	Route::any('/', [LoginController::class, 'login']);
	Route::any('/login', [LoginController::class, 'login'])->name('admin.login');
	Route::middleware(['admin', 'CheckPermission'])->group(static function () {
		//::users route
		Route::any('user/delete', 'UsersController@delete')->name('users.delete');
		Route::any('dashboard', 'UsersController@dashboard')->name('admin.dashboard');
		Route::any('user/profile', 'UsersController@profile')->name('admin.profile');
		Route::any('user/change-password', 'UsersController@changePassword')->name('admin.change-password');
		Route::any('user/status', 'UsersController@status')->name('users.status');
		Route::any('app-setting', 'UsersController@appSetting')->name('admin.app-setting');
		Route::any('export', 'UsersController@export')->name('admin.users.export');
		Route::any('pdf', 'UsersController@createPDF')->name('admin.users.export-pdf');
		Route::resource('users', UsersController::class);

		//  admins route
		Route::post('admins/delete', 'AdminsController@delete')->name('admins.delete');
		Route::post('admins/status', 'AdminsController@status')->name('admins.status');
		Route::resource('admins', AdminsController::class);

		//  roles route
		Route::post('roles/delete', 'RolesController@delete')->name('roles.delete');
		Route::post('roles/status', 'RolesController@status')->name('roles.status');
		Route::any('roles/permissions/{id?}', 'RolesController@permissions')->name('roles.permissions');
		Route::resource('roles', RolesController::class);

		//  template route
		Route::post('template/status', 'TemplatesController@status')->name('templates.status');
		Route::resource('templates', TemplatesController::class);

		// page routes
		Route::post('pages/status', 'CmsController@status')->name('pages.status');
		Route::resource('pages', CmsController::class);

		//::site setting
		Route::resource('settings', SettingsController::class);
		Route::any('/logout', [LoginController::class, 'logout'])->name('admin.logout');
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();
// Route::get('send-mail', [MailController::class, 'sendMail'])->name('sendMail');

Route::group(['namespace' => 'Front'], function () {
	Route::get('/', 'HomeController@index')->name('front.home.index');
	Route::get('/page/{slug}', 'PagesController@AppPages');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;
use App\Scopes\HasActiveScope;

class User extends Authenticatable implements JWTSubject
{

    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',  'last_name', 'email', 'phone_no', 'password', 'profile_picture', 'gender', 'register_with', 'token', 'country_code', 'status', 'otp_code', 'deleted_at', 'description', 'role'
    ];
    protected $appends = ['name'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public static function getProfile($id)
    {
        $user = User::where('id', '=', $id)->first();
        return $user;
    }
    public function getNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;
use App\Models\User;
use App\Models\Admin;
use App\Models\AppSetting;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Hash;
use DataTables;
use App\Lib\Helper;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\File;
use Excel;
use App\Exports\ExportData;
use PDF;

class UsersController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index(Request $request)
  {
    $breadcrumbs = [
      ['name' => 'Users', 'relation' => 'Current', 'url' => '']
    ];
    $page_title = 'Users List';
    if ($request->ajax()) {
      $users = User::orderBy('id', 'desc');
      return DataTables::of($users)
        ->addColumn('action', function ($user) {
          $user_id = Crypt::encrypt($user->id);
          $btn = '<a title="Edit" href="' . route('users.edit', $user_id) . '" class="btn btn-xs btn-info"><i class="fas fa-edit"></i></a>&nbsp;';
          $btn .= '<a title="View" href="' . route('users.show', $user_id) . '" class="btn btn-xs btn-primary"><i class="fas fa-eye"></i></a>&nbsp;';
          $btn .= '<a title="Delete" data-link="' . route('users.delete') . '" id="delete_' . $user->id . '" onclick="confirm_delete(' . $user->id . ')" href="javascript:void(0)" class="btn btn-xs btn-danger"><i class="fas fa-trash"></i></a>&nbsp;';
          return $btn;
        })
        ->editColumn('status', function ($user) {
          return Helper::getStatus($user->status, $user->id, route('users.status'));
        })
        ->editColumn('created_at', function ($user) {
          return getformattedDate($user->created_at);
        })
        ->filter(function ($instance) use ($request) {
          if ($request->get('status') == '0' || $request->get('status') == '1') {
            $instance->where('status', $request->get('status'));
          }
          if (!empty($request->get('search'))) {
            $instance->where(function ($w) use ($request) {
              $search = $request->get('search');
              $w->orWhere('first_name', 'LIKE', "%$search%")
                ->orWhere('email', 'LIKE', "%$search%");
            });
          }
        })
        ->rawColumns(['status', 'action'])
        ->make(true);
    }
    return view('Admin.Users.index', compact('page_title', 'breadcrumbs'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    try {
      $page_title = 'Add User';
      $breadcrumbs = [
        ['name' => 'Users', 'relation' => 'link', 'url' => route('users.index')],
        ['name' => 'Add User', 'relation' => 'Current', 'url' => '']
      ];
      return view('Admin.Users.create', compact('page_title', 'breadcrumbs'));
    } catch (\Throwable $th) {
      return ['status' => 'false', 'message' => $th->getMessage()];
    }
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    DB::beginTransaction();
    try {
      if ($request->isMethod('post')) {
        $postdata  = $request->all();
        $rules = [
          'first_name' => 'required|max:50',
          'last_name' => 'required|max:50',
          'phone_no' => 'required|unique:users,phone_no',
          'email' => 'required|email|unique:users,email',
          'description' => 'required',
          'profile_picture' => 'nullable'
        ];

        $validator = Validator::make($postdata, $rules);
        if ($validator->fails()) {
          return response()->json(array('errors' => $validator->errors()), 422);
        } else {
          $postdata['register_with'] = 'ADMIN';
          if ($request->hasFile('profile_picture')) {
            $img = $request->file('profile_picture');
            $file_ext = $img->getClientOriginalExtension();
            $filename = time() . '.' . $file_ext;
            $destination_path = 'uploads/users/' . $filename;
            if (Storage::disk('public')->put($destination_path, file_get_contents($img->getRealPath()))) {
              $postdata['profile_picture'] = 'public/' . $destination_path;
            }
          }
          User::create($postdata);
          DB::commit();
          Session::flash('success', 'User Create Successfully');
          return ['status' => 'true', 'message' => 'User Create Successfully.'];
        }
      }
    } catch (\Throwable $th) {
      DB::rollBack();
      return ['status' => 'false', 'message' => $th->getMessage()];
    }
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    $id = Crypt::decrypt($id);
    $page_title = 'View User';
    $breadcrumbs = [
      ['name' => 'Users', 'relation' => 'link', 'url' => route('users.index')],
      ['name' => 'View User', 'relation' => 'Current', 'url' => '']
    ];
    $data = User::where('id', $id)->first();
    if ($data) {
      $page_title = "Profile - " . $data->name;
      return view('Admin.Users.view', compact('page_title', 'data', 'breadcrumbs'));
    } else {
      return abort(404);
    }
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    try {
      $id = Crypt::decrypt($id);
      $getuser = User::findOrFail($id);
      $page_title = 'Edit User';
      $breadcrumbs = [
        ['name' => 'Users', 'relation' => 'link', 'url' => route('users.index')],
        ['name' => 'Edit User', 'relation' => 'Current', 'url' => '']
      ];
      return view('Admin.Users.edit', compact('page_title', 'breadcrumbs', 'getuser', 'id'));
    } catch (\Throwable $th) {
      return ['status' => 'false', 'message' => $th->getMessage()];
    }
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    DB::beginTransaction();
    try {
      $getuser = User::findOrFail($id);
      $postdata  = $request->all();
      $rules = [
        'first_name' => 'required|max:50',
        'last_name' => 'required|max:50',
        'phone_no' => 'required|unique:users,phone_no,' . $id,
        'email' => 'required|email|unique:users,email,' . $id,
        'description' => 'required',
        'profile_picture' => 'nullable'
      ];
      $validator = Validator::make($postdata, $rules);
      if ($validator->fails()) {
        return response()->json(array('errors' => $validator->errors()), 422);
      } else {

        if ($request->hasFile('profile_picture')) {
          $img = $request->file('profile_picture');
          $file_ext = $img->getClientOriginalExtension();
          $filename = time() . '.' . $file_ext;
          $destination_path = 'uploads/users/' . $filename;
          if (Storage::disk('public')->put($destination_path, file_get_contents($img->getRealPath()))) {
            $postdata['profile_picture'] = 'public/' . $destination_path;
          }
        } else {
          $postdata['profile_picture'] = $getuser->profile_picture;
        }
        $getuser->update($postdata);
        DB::commit();
        Session::flash('success', 'User update Successfully');
        return ['status' => 'true', 'message' => 'User update Successfully.'];
      }
    } catch (\Throwable $th) {
      DB::rollBack();
      return ['status' => 'false', 'message' => $th->getMessage()];
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function delete(Request $request)
  {
    try {
      $data = User::where('id', $request->id)->first();
      File::delete($data->profile_picture);
      if ($data->delete()) {
        return ['status' => 'true', 'message' => 'User delete Successfully'];
      } else {
        return abort(404);
      }
    } catch (\Throwable $th) {
      return ['status' => 'false', 'message' => $th->getMessage()];
    }
  }



  public function dashboard()
  {
    try {
      $page_title = 'Dashboard';
      // total users
      $total_users = User::where(['role' => 'user'])->count();
      // active users
      $active_users = User::where(['status' => '1', 'role' => 'user'])->count();
      // new users
      $new_users = User::where(['status' => '1', 'role' => 'user', 'created_at' => date('Y-m-d')])->count();
      return view('Admin.Users.dashboard', compact('total_users', 'page_title', 'active_users', 'new_users'));
    } catch (\Throwable $th) {
      return ['status' => 'false', 'message' => $th->getMessage()];
    }
  }
  public function profile(Request $request)
  {
    DB::beginTransaction();
    try {
      $page_title = 'Admin Profile';
      $id = Auth::guard('admin')->user()->id;
      $user = Admin::findorFail($id);
      $postdata = $request->all();

      if ($request->isMethod('patch')) {
        $rules = [
          'name' => 'required',
          'email' => 'required|email|unique:users,email,' . $id,
          'profile_picture' => 'nullable',
        ];

        $validator = Validator::make($postdata, $rules);
        if ($validator->fails()) {
          return response()->json(array('errors' => $validator->errors()), 422);
        } else {

          if ($request->hasFile('profile_picture')) {
            $img = $request->file('profile_picture');
            $file_ext = $img->getClientOriginalExtension();
            $filename = time() . '.' . $file_ext;

resources/views/Admin/Users/app-setting.blade.php
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ $title }}</h4>
                    <hr>
                    {{ Form::model($data, ['files' => 'true', 'class' => '', 'id' => 'submit-form', 'autocomplete' => 'off']) }}
                    <div class="form-group">
                        <label>Android Version</label>
                        {{ Form::text('android_version', null, ['placeholder' => 'Android App version', 'id' => 'android_version', 'class' => 'form-control']) }}
                    </div>

                    <div class="form-group">
                        <label>Ios Version</label>
                        {{ Form::text('ios_version', null, ['placeholder' => 'Ios App version', 'id' => 'ios_version', 'class' => 'form-control']) }}
                    </div>
                    <div class="form-group">
                        <label>Android Force Update</label><br>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="android_force_update"
                                {{ $data->android_force_update == 1 ? 'checked' : '' }} class="custom-control-input"
                                id="android_force_update" value="1">
                            <label class="custom-control-label" for="android_force_update">Yes</label>
                        </div>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="android_force_update" class="custom-control-input"
                                id="android_force_update1" value="0"
                                {{ $data->android_force_update == 0 ? 'checked' : '' }}>
                            <label class="custom-control-label" for="android_force_update1">No</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Ios Force Update</label><br>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="ios_force_update"
                                {{ $data->ios_force_update == 1 ? 'checked' : '' }} class="custom-control-input"
                                id="ios_force_update" value="1">
                            <label class="custom-control-label" for="ios_force_update">Yes</label>
                        </div>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="ios_force_update" class="custom-control-input" id="ios_force_update1"
                                value="0" {{ $data->ios_force_update == 0 ? 'checked' : '' }}>
                            <label class="custom-control-label" for="ios_force_update1">No</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Android Maintenance</label><br>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="android_maintenance" class="custom-control-input"
                                {{ $data->android_maintenance == 1 ? 'checked' : '' }} id="android_maintenance1"
                                value="1">
                            <label class="custom-control-label" for="android_maintenance1">Yes</label>
                        </div>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="android_maintenance" class="custom-control-input"
                                id="android_maintenance" value="0" {{ $data->android_maintenance == 0 ? 'checked' : '' }}>
                            <label class="custom-control-label" for="android_maintenance">No</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Ios Maintenance</label><br>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="ios_maintenance" class="custom-control-input"
                                {{ $data->ios_maintenance == 1 ? 'checked' : '' }} id="ios_maintenance1" value="1">
                            <label class="custom-control-label" for="ios_maintenance1">Yes</label>
                        </div>
                        <div class="custom-control custom-checkbox mr-sm-2">
                            <input type="radio" name="ios_maintenance" class="custom-control-input" id="ios_maintenance"
                                value="0" {{ $data->ios_maintenance == 0 ? 'checked' : '' }}>
                            <label class="custom-control-label" for="ios_maintenance">No</label>
                        </div>
                    </div>
                    <button class="btn btn-primary" id="submit-btn" type="submit"><span id="licon"></span>Save</button>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>

@endsection


@section('scripts')
    <script>
        $('#submit-form').ajaxForm({
            beforeSubmit: function() {
                $(".error").remove();
                disable("#submit-btn", true);
            },
            error: function(err) {
                handleError(err);
                disable("#submit-btn", false);
            },
            success: function(response) {
                disable("#submit-btn", false);
                if (response.status == 'true') {
                    Alert(response.message, true);
                } else {
                    Alert(response.message, false);
                }
            }
        });
    </script>
@endsection

resources/views/Admin/Users/change_password.blade.php
@extends('layouts.admin.admin')
@section('content')
    <div class="content">
        <div class="card">
            <div class="card-body">
                {!! Form::open(['route' => ['admin.change-password'], 'files' => 'true', 'id' => 'submit-form']) !!}
                @method('PATCH')
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="inputEmail">Old Password</label>
                            <?= Form::password('old_password', ['class' => 'form-control', 'placeholder' => 'Password', 'id' => 'old_password']) ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="inputEmail">Password</label>
                            <?= Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password', 'id' => 'password']) ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="inputName">Confirm Password</label>
                            <?= Form::password('password_confirmation', ['class' => 'form-control', 'placeholder' => 'Confirm Password', 'id' => 'password_confirmation']) ?>
                        </div>
                    </div>
                    <div class="col-lg-12" style="margin: 1% 0;"></div>
                    <div class="col-sm-2">
                        {!! Form::button('<span id="licon"></span>Update', ['class' => 'btn btn-primary', 'id' => 'submit-btn', 'type' => 'submit']) !!}
                    </div>
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(function() {
            $('#submit-form').ajaxForm({
                beforeSubmit: function() {
                    $(".error").remove();
                    disable("#submit-btn", true);
                },
                error: function(err) {
                    handleError(err);
                    disable("#submit-btn", false);
                },
                success: function(response) {
                    disable("#submit-btn", false);
                    if (response.status == 'true') {
                        window.location.href = '{{ route('admin.change-password') }}';
                    } else {
                        Alert(response.message, false);
                    }
                }
            });
        });
    </script>
@endsection

resources/views/Admin/Users/create.blade.php
@php
$role_list = Config::get('params.role_list');
@endphp
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {!! Form::open(['route' => ['users.store'], 'files' => 'true', 'class' => '', 'id' => 'submit-form', 'autocomplete' => 'off']) !!}
                    @method('POST')
                    @include('Admin.Users.form');
                    {!! Form::button('<span id="licon"></span>Save', ['class' => 'btn btn-primary', 'id' => 'submit-btn', 'type' => 'submit']) !!}
                    <a class="btn btn-secondary" href="{{ route('users.index') }}">Back</a>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function() {
            $('#submit-form').ajaxForm({
                beforeSubmit: function() {
                    $(".error").remove();
                    disable("#submit-btn", true);
                },
                error: function(err) {
                    handleError(err);
                    disable("#submit-btn", false);
                },
                success: function(response) {
                    disable("#submit-btn", false);
                    if (response.status == 'true') {
                        window.location.href = '{{ route('users.index') }}';
                    } else {
                        Alert(response.message, false);
                    }
                }
            });
        });
    </script>
@endsection

resources/views/Admin/Users/dashboard.blade.php
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-sm-6 col-md-3">
            <div class="card card-stats card-round">
                <div class="card-body ">
                    <div class="row align-items-center">
                        <div class="col-icon">
                            <div class="icon-big text-center icon-primary bubble-shadow-small">
                                <i class="flaticon-users"></i>
                            </div>
                        </div>
                        <div class="col col-stats ml-3 ml-sm-0">
                            <div class="numbers">
                                <p class="card-category">Total Users</p>
                                <h4 class="card-title">{{ $total_users }}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-3">
            <div class="card card-stats card-round">
                <div class="card-body ">
                    <div class="row align-items-center">
                        <div class="col-icon">
                            <div class="icon-big text-center icon-primary bubble-shadow-small">
                                <i class="flaticon-list"></i>
                            </div>
                        </div>
                        <div class="col col-stats ml-3 ml-sm-0">
                            <div class="numbers">
                                <p class="card-category">Active Users</p>
                                <h4 class="card-title">{{ $active_users }}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('scripts')
    <script src="{{ url('public/admin/js/setting-demo.js') }}"></script>
    <script src="{{ url('public/admin/js/demo.js') }}"></script>
@endsection

resources/views/Admin/Users/index.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">

                <div class="form-group">
                    <label><strong>Status :</strong></label>
                    <select id='status' class="form-control" style="width: 200px">
                        <option value="">--Select Status--</option>
                        <option value="1">Active</option>
                        <option value="0">Deactive</option>
                    </select>

                </div>
                <div class="text-right mb-3">
                    <a href="{{ route('users.create') }}" class="btn btn-secondary">Add New</a>
                    <a class="btn btn-warning export" href="javascript:void(0)">Export to Excel</a>
                    <a class="btn btn-primary pdf" href="javascript:void(0)">Export to PDF</a>
                </div>
                <div class="row">
                    <div class="table-responsive">
                        <table id="users-table" class="display table table-striped table-hover w-100">
                            <thead>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone Number</th>
                                <th>Created on</th>
                                <th>Status</th>
                                <th width="100">Action</th>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
<script>
    $(function() {
        var table = $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('users.index') }}",
                data: function(d) {
                    d.status = $('#status').val(),
                        d.search = $('input[type="search"]').val()
                }
            },

            columns: [{
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'phone_no',
                    name: 'phone_no'
                },
                {
                    data: 'created_at',
                    name: 'created_at'
                },
                {
                    data: 'status',
                    name: 'status',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false
                }
            ],
            order: [
                [0, 'desc']
            ]
        });
        $('#status').change(function() {
            table.draw();
        });
    });

    // export user data
    $(document).on("click", ".export", function() {
        var status = $("#status").val();
        var route = "{{ route('admin.users.export') }}";
        route += '?status=' + status;
        window.location.href = route;
    });

    // export user data
    $(document).on("click", ".pdf", function() {
        var status = $("#status").val();
        var route = "{{ route('admin.users.export-pdf') }}";
        route += '?status=' + status;
        window.location.href = route;
    });
    
</script>
@endsection