routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;
use App\Http\Controllers\Admin\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin'], function () {
	Route::any('/', [LoginController::class, 'login']);
	Route::any('/login', [LoginController::class, 'login'])->name('admin.login');
	Route::middleware(['admin', 'CheckPermission'])->group(static function () {
		//::users route
		Route::any('user/delete', 'UsersController@delete')->name('users.delete');
		Route::any('dashboard', 'UsersController@dashboard')->name('admin.dashboard');
		Route::any('user/profile', 'UsersController@profile')->name('admin.profile');
		Route::any('user/change-password', 'UsersController@changePassword')->name('admin.change-password');
		Route::any('user/status', 'UsersController@status')->name('users.status');
		Route::any('app-setting', 'UsersController@appSetting')->name('admin.app-setting');
		Route::any('export', 'UsersController@export')->name('admin.users.export');
		Route::any('pdf', 'UsersController@createPDF')->name('admin.users.export-pdf');
		Route::resource('users', UsersController::class);

		//  admins route
		Route::post('admins/delete', 'AdminsController@delete')->name('admins.delete');
		Route::post('admins/status', 'AdminsController@status')->name('admins.status');
		Route::resource('admins', AdminsController::class);

		//  roles route
		Route::post('roles/delete', 'RolesController@delete')->name('roles.delete');
		Route::post('roles/status', 'RolesController@status')->name('roles.status');
		Route::any('roles/permissions/{id?}', 'RolesController@permissions')->name('roles.permissions');
		Route::resource('roles', RolesController::class);

		//  template route
		Route::post('template/status', 'TemplatesController@status')->name('templates.status');
		Route::resource('templates', TemplatesController::class);

		// page routes
		Route::post('pages/status', 'CmsController@status')->name('pages.status');
		Route::resource('pages', CmsController::class);

		//::site setting
		Route::resource('settings', SettingsController::class);
		Route::any('/logout', [LoginController::class, 'logout'])->name('admin.logout');
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();
// Route::get('send-mail', [MailController::class, 'sendMail'])->name('sendMail');

Route::group(['namespace' => 'Front'], function () {
	Route::get('/', 'HomeController@index')->name('front.home.index');
	Route::get('/page/{slug}', 'PagesController@AppPages');
});

resources/views/Admin/admins/create.blade.php
@php
$role_list = Config::get('params.role_list');
@endphp
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {!! Form::open(['route' => ['admins.store'], 'files' => 'true', 'class' => '', 'id' => 'submit-form', 'autocomplete' => 'off']) !!}
                    @method('POST')
                    @include('Admin.admins.form');
                    {!! Form::button('<span id="licon"></span>Save', ['class' => 'btn btn-primary', 'id' => 'submit-btn', 'type' => 'submit']) !!}
                    <a class="btn btn-secondary" href="{{ route('admins.index') }}">Back</a>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function() {
            $('#submit-form').ajaxForm({
                beforeSubmit: function() {
                    $(".error").remove();
                    disable("#submit-btn", true);
                },
                error: function(err) {
                    handleError(err);
                    disable("#submit-btn", false);
                },
                success: function(response) {
                    disable("#submit-btn", false);
                    if (response.status == 'true') {
                        window.location.href = '{{ route('admins.index') }}';
                    } else {
                        Alert(response.message, false);
                    }
                }
            });
        });
    </script>
@endsection

resources/views/Admin/admins/edit.blade.php
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {!! Form::model($data, ['route' => ['admins.update', [$id]], 'files' => 'true', 'class' => '', 'id' => 'submit-form', 'autocomplete' => 'off']) !!}
                    @csrf
                    @method('PATCH')
                    @include('Admin.admins.form');
                    {!! Form::button('<span id="licon"></span>Save', ['class' => 'btn btn-primary', 'id' => 'submit-btn', 'type' => 'submit']) !!}
                    <a class="btn btn-secondary" href="{{ route('admins.index') }}">Back</a>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function() {
            $('#submit-form').ajaxForm({
                beforeSubmit: function() {
                    $(".error").remove();
                    disable("#submit-btn", true);
                },
                error: function(err) {
                    handleError(err);
                    disable("#submit-btn", false);
                },
                success: function(response) {
                    disable("#submit-btn", false);
                    if (response.status == 'true') {
                        window.location.href = '{{ route('admins.index') }}';
                    } else {
                        Alert(response.message, false);
                    }
                }
            });
        });
    </script>
@endsection

resources/views/Admin/admins/form.blade.php
<div class=" p-4">
    <div class="form-row">

        <div class="form-group col-md-6">
            <label for="name">Name </label>
            <?= Form::text('name', null, ['placeholder' => 'Name', 'class' => 'form-control', 'required' => true, 'id' => 'first_name']) ?>
        </div>

        <div class="form-group col-md-6">
            <label for="email">Email Address</label>
            <?= Form::email('email', null, ['placeholder' => 'Email Address', 'class' => 'form-control', 'required' => true, 'id' => 'email']) ?>
        </div>

        <div class="form-group col-md-6">
            <label for="phone_number">Phone Number</label>
            <?= Form::text('phone_number', null, ['placeholder' => 'Phone Number', 'class' => 'form-control', 'id' => 'phone_number']) ?>
        </div>

        <div class="form-group col-md-6">
            <label for="role_id">Role</label>
            <?= Form::select('role_id', $roles, null, ['placeholder' => 'Choose...', 'class' => 'form-control', 'required' => true, 'id' => 'role_id']) ?>
        </div>



    </div>
</div>

resources/views/Admin/admins/index.blade.php
@extends('layouts.admin.admin')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="text-right mb-2">
                        <a href="{{ route('admins.create') }}" class="btn btn-secondary btn-md">Add New</a>
                    </div>
                    <div class="row">
                        <div class="table-responsive">
                            <table id="users-table" class="display table table-striped table-hover w-100">
                                <thead>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone Number</th>
                                    <th>Created on</th>
                                    <th>Status</th>
                                    <th width="100">Action</th>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(function() {
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{!! route('admins.index') !!}",
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'email',
                        name: 'email'
                    },
                    {
                        data: 'phone_number',
                        name: 'phone_number'
                    },
                    {
                        data: 'created_at',
                        name: 'created_at'
                    },
                    {
                        data: 'status',
                        name: 'status',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    }
                ],
                order: [
                    [0, 'desc']
                ]
            });
        })
    </script>
@endsection