routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;
use App\Http\Controllers\Admin\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin'], function () {
	Route::any('/', [LoginController::class, 'login']);
	Route::any('/login', [LoginController::class, 'login'])->name('admin.login');
	Route::middleware(['admin', 'CheckPermission'])->group(static function () {
		//::users route
		Route::any('user/delete', 'UsersController@delete')->name('users.delete');
		Route::any('dashboard', 'UsersController@dashboard')->name('admin.dashboard');
		Route::any('user/profile', 'UsersController@profile')->name('admin.profile');
		Route::any('user/change-password', 'UsersController@changePassword')->name('admin.change-password');
		Route::any('user/status', 'UsersController@status')->name('users.status');
		Route::any('app-setting', 'UsersController@appSetting')->name('admin.app-setting');
		Route::any('export', 'UsersController@export')->name('admin.users.export');
		Route::any('pdf', 'UsersController@createPDF')->name('admin.users.export-pdf');
		Route::resource('users', UsersController::class);

		//  admins route
		Route::post('admins/delete', 'AdminsController@delete')->name('admins.delete');
		Route::post('admins/status', 'AdminsController@status')->name('admins.status');
		Route::resource('admins', AdminsController::class);

		//  roles route
		Route::post('roles/delete', 'RolesController@delete')->name('roles.delete');
		Route::post('roles/status', 'RolesController@status')->name('roles.status');
		Route::any('roles/permissions/{id?}', 'RolesController@permissions')->name('roles.permissions');
		Route::resource('roles', RolesController::class);

		//  template route
		Route::post('template/status', 'TemplatesController@status')->name('templates.status');
		Route::resource('templates', TemplatesController::class);

		// page routes
		Route::post('pages/status', 'CmsController@status')->name('pages.status');
		Route::resource('pages', CmsController::class);

		//::site setting
		Route::resource('settings', SettingsController::class);
		Route::any('/logout', [LoginController::class, 'logout'])->name('admin.logout');
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();
// Route::get('send-mail', [MailController::class, 'sendMail'])->name('sendMail');

Route::group(['namespace' => 'Front'], function () {
	Route::get('/', 'HomeController@index')->name('front.home.index');
	Route::get('/page/{slug}', 'PagesController@AppPages');
});

resources/views/Admin/pages/create.blade.php
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {!! Form::open(['route' => ['pages.store'], 'files' => 'true', 'class' => '', 'id' => 'submit-form', 'autocomplete' => 'off']) !!}
                    @method('POST')
                    @include('Admin.pages.form');
                    {!! Form::button('<span id="licon"></span>Save', ['class' => 'btn btn-primary', 'id' => 'submit-btn', 'type' => 'submit']) !!}
                    <a class="btn btn-secondary" href="{{ route('pages.index') }}">Back</a>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $('#description').summernote({
            height: 300
        });

        $(function() {
            $('#submit-form').ajaxForm({
                beforeSubmit: function() {
                    $(".error").remove();
                    disable("#submit-btn", true);
                },
                error: function(err) {
                    handleError(err);
                    disable("#submit-btn", false);
                },
                success: function(response) {
                    disable("#submit-btn", false);
                    if (response.status == 'true') {
                        window.location.href = '{{ route('pages.index') }}';
                    } else {
                        Alert(response.message, false);
                    }
                }
            });
        });
    </script>
@endsection

resources/views/Admin/pages/edit.blade.php
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {!! Form::model($data, ['route' => ['pages.update', [$id]], 'files' => 'true', 'class' => '', 'id' => 'submit-form', 'autocomplete' => 'off']) !!}
                    @csrf
                    @method('PATCH')
                    @include('Admin.pages.form');
                    {!! Form::button('<span id="licon"></span>Save', ['class' => 'btn btn-primary', 'id' => 'submit-btn', 'type' => 'submit']) !!}
                    <a class="btn btn-secondary" href="{{ route('pages.index') }}">Back</a>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $('#description').summernote({
            height: 300
        });

        $(function() {
            $('#submit-form').ajaxForm({
                beforeSubmit: function() {
                    $(".error").remove();
                    disable("#submit-btn", true);
                },
                error: function(err) {
                    handleError(err);
                    disable("#submit-btn", false);
                },
                success: function(response) {
                    disable("#submit-btn", false);
                    if (response.status == 'true') {
                        window.location.href = '{{ route('pages.index') }}';
                    } else {
                        Alert(response.message, false);
                    }
                }
            });
        });
    </script>
@endsection

resources/views/Admin/pages/form.blade.php
<div class="form-group">
    <label>Page Tttle</label>
    {{ Form::text('title', null, ['placeholder' => 'Page title', 'id' => 'title', 'class' => 'form-control']) }}
</div>
<div class="form-group">
    <label>Page Slug</label>
    {{ Form::text('slug', null, ['placeholder' => 'Page Slug', 'id' => 'slug', 'readonly' => 'readonly', 'class' => 'form-control']) }}
</div>
<div class="form-group">
    <label>Description</label>
    {{ Form::textarea('description', null, ['placeholder' => 'description Slug', 'id' => 'description', 'class' => 'form-control']) }}
</div>

<script>
    $("#title").keyup(function() {
        var Text = $(this).val();
        Text = convertToName($.trim(Text));
        $("#slug").val(Text);
    });
    $("#title").change(function() {
        var Text = $(this).val();
        Text = convertToName($.trim(Text));
        $("#slug").val(Text);
    });
</script>

resources/views/Admin/pages/index.blade.php
@extends('layouts.admin.admin')
@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="text-right mb-3">
                        <a href="{{ route('pages.create') }}" class="btn btn-secondary">Add New</a>
                    </div>
                    <div class="row">
                        <div class="table-responsive">
                            <table id="users-table" class="display table table-striped table-hover w-100">
                                <thead>
                                    <th>id</th>
                                    <th>Page Title</th>
                                    <th>Page Slug</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(function() {
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('pages.index') !!}',
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'title',
                        name: 'title'
                    },
                    {
                        data: 'slug',
                        name: 'slug'
                    },
                    {
                        data: 'status',
                        name: 'status'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    }
                ]
            });
        })
    </script>
@endsection

resources/views/Admin/pages/view.blade.php
@extends('layouts.admin.admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-lg-12">

                        <hr>
                        <div style="text-align:center">
                            <div class="row">
                                <div class="col-md-12 col-xs-6 b-r m-b-15"> <strong>Title</strong>
                                    <br>
                                    <p class="text-muted">{{ @$data['title'] ? $data['title'] : '' }}</p>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-12 col-xs-6 b-r m-b-15"> <strong>FAQ Description</strong>
                                    <br>
                                    <p class="text-muted">{!! $data->description !!}</p>
                                </div>

                            </div>
                        </div>
                        <div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <a class="btn btn-success" href="javascript:void(0)" onclick="goBack()">Go Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection