routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;
use App\Http\Controllers\Admin\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin'], function () {
	Route::any('/', [LoginController::class, 'login']);
	Route::any('/login', [LoginController::class, 'login'])->name('admin.login');
	Route::middleware(['admin', 'CheckPermission'])->group(static function () {
		//::users route
		Route::any('user/delete', 'UsersController@delete')->name('users.delete');
		Route::any('dashboard', 'UsersController@dashboard')->name('admin.dashboard');
		Route::any('user/profile', 'UsersController@profile')->name('admin.profile');
		Route::any('user/change-password', 'UsersController@changePassword')->name('admin.change-password');
		Route::any('user/status', 'UsersController@status')->name('users.status');
		Route::any('app-setting', 'UsersController@appSetting')->name('admin.app-setting');
		Route::any('export', 'UsersController@export')->name('admin.users.export');
		Route::any('pdf', 'UsersController@createPDF')->name('admin.users.export-pdf');
		Route::resource('users', UsersController::class);

		//  admins route
		Route::post('admins/delete', 'AdminsController@delete')->name('admins.delete');
		Route::post('admins/status', 'AdminsController@status')->name('admins.status');
		Route::resource('admins', AdminsController::class);

		//  roles route
		Route::post('roles/delete', 'RolesController@delete')->name('roles.delete');
		Route::post('roles/status', 'RolesController@status')->name('roles.status');
		Route::any('roles/permissions/{id?}', 'RolesController@permissions')->name('roles.permissions');
		Route::resource('roles', RolesController::class);

		//  template route
		Route::post('template/status', 'TemplatesController@status')->name('templates.status');
		Route::resource('templates', TemplatesController::class);

		// page routes
		Route::post('pages/status', 'CmsController@status')->name('pages.status');
		Route::resource('pages', CmsController::class);

		//::site setting
		Route::resource('settings', SettingsController::class);
		Route::any('/logout', [LoginController::class, 'logout'])->name('admin.logout');
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();
// Route::get('send-mail', [MailController::class, 'sendMail'])->name('sendMail');

Route::group(['namespace' => 'Front'], function () {
	Route::get('/', 'HomeController@index')->name('front.home.index');
	Route::get('/page/{slug}', 'PagesController@AppPages');
});

resources/views/Admin/includes/footer.blade.php
<footer class="footer">
        <div class="container-fluid">
          <nav class="pull-left">
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  Help
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  Licenses
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </footer>

resources/views/Admin/includes/header.blade.php
<div class="user">
    @if (isset(Auth::guard('admin')->user()->profile_picture) && file_exists(Auth::guard('admin')->user()->profile_picture))
        <div class="avatar-sm float-left mr-2">
            <img src="{{ url(Auth::guard('admin')->user()->profile_picture) }}" alt="..."
                class="avatar-img rounded-circle">
        </div>
    @else
        <div class="avatar-sm float-left mr-2">
            <img src="{{ url('public/admin/img/default-user.png') }}" alt="..." class="avatar-img rounded-circle">
        </div>
    @endif
    <div class="info">
        <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
            <span>
                {{ Auth::guard('admin')->user()->name }}
                <span class="user-level">Administrator</span>
                <span class="caret"></span>
            </span>
        </a>
        <div class="clearfix"></div>
        <div class="collapse in" id="collapseExample">
            <ul class="nav">
                <li>
                    <a href="{{ route('admin.profile') }}">
                        <span class="link-collapse">My Profile</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.logout') }}">
                        <span class="link-collapse">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

resources/views/Admin/includes/messages.blade.php
    @if (session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if (session('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if (session('warning'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ session('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if (session('info'))
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            {{ session('info') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if (session('primary'))
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            {{ session('primary') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif


    @if (session('secondary'))
        <div class="alert alert-secondary alert-dismissible fade show" role="alert">
            {{ session('secondary') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if (session('dark'))
        <div class="alert alert-dark alert-dismissible fade show" role="alert">
            {{ session('dark') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

resources/views/Admin/includes/navbar.blade.php
<div class="main-header">
    <!-- Logo Header -->
    <div class="logo-header" data-background-color="white">

        <a href="{{ route('admin.dashboard') }}" class="logo">
            <img src="{{ url('public/Admin/img/logo.png') }}" alt="Admin Logo" class="navbar-brand" height="95%"
                width="85%">
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class="icon-menu"></i>
            </span>
        </button>
        <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
        <div class="nav-toggle">
            <button class="btn btn-toggle toggle-sidebar">
                <i class="icon-menu"></i>
            </button>
        </div>
    </div>
    <!-- End Logo Header -->
    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">


        <div class="container-fluid">
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                {{-- @if (Session::has('success'))
                    <div class="alert alert-danger text-center alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Great!</strong> {{ Session::get('success') }}
                    </div>
                @endif --}}



                <li class="nav-item dropdown hidden-caret">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <div class="avatar-sm">
                            @if (file_exists(Auth::guard('admin')->user()->profile_picture))
                                <img src="{{ url(Auth::guard('admin')->user()->profile_picture) }}" alt="..."
                                    class="avatar-img rounded-circle">
                            @else
                                <img src="{{ url('public/admin/img/default-user.png') }}" alt="..."
                                    class="avatar-img rounded-circle">
                            @endif
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated fadeIn">
                        <div class="dropdown-user-scroll scrollbar-outer">
                            <li>
                                <div class="user-box">
                                    <div class="avatar-lg">
                                        @if (file_exists(Auth::guard('admin')->user()->profile_picture))
                                            <img src="{{ url(Auth::guard('admin')->user()->profile_picture) }}"
                                                alt="..." class="avatar-img rounded">
                                        @else
                                            <img src="{{ url('public/admin/img/default-user.png') }}" alt="..."
                                                class="avatar-img rounded">
                                        @endif
                                    </div>
                                    <div class="u-text">
                                        <h4>{{ Auth::guard('admin')->user()->name }}</h4>
                                        <p class="text-muted">{{ Auth::guard('admin')->user()->email }}</p>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ route('admin.profile') }}">My Profile</a>
                                <a class="dropdown-item" href="{{ route('admin.change-password') }}">Change
                                    Password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ route('admin.app-setting') }}">App Settings</a>
                                <a class="dropdown-item" href="{{ route('settings.index') }}">Site Settings</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ route('admin.logout') }}">Logout</a>
                            </li>
                        </div>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <!-- End Navbar -->
</div>

resources/views/Admin/includes/sidebar.blade.php
@php
$action = app('request')
    ->route()
    ->getAction();
$controller = class_basename($action['controller']);
[$controller, $action] = explode('@', $controller);
@endphp


<div class="sidebar sidebar-style-2">
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            @include('Admin.includes.header')
            <ul class="nav nav-primary">
                <li class="nav-item {{ request()->is('admin/dashboard') ? 'active submenu' : '' }}">
                    <a href="{{ route('admin.dashboard') }}">
                        <i class="fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <!-- users Management -->
                @if ($role_permissions == -1 || in_array('UsersController', $role_permissions))
                    <li
                        class="nav-item {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active submenu' : '' }}">
                        <a data-toggle="collapse" href="#users">
                            <i class="fas fa-user"></i>
                            <p>Users Management</p>
                            <span class="caret"></span>
                        </a>

                        <div class="collapse {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'show' : '' }}"
                            id="users">
                            <ul class="nav nav-collapse">
                                <li
                                    class="{{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                    <a href="{{ route('users.index') }}">
                                        <span class="sub-item">List of Users</span>
                                    </a>
                                </li>

                              
                            </ul>
                        </div>
                    </li>
                @endif
                <!-- role Management -->
                @if ($role_permissions == -1 || in_array('AdminsController', $role_permissions))
                    <li
                        class="nav-item {{ request()->is('admin/roles') || request()->is('admin/roles/*') || request()->is('admin/admins') || request()->is('admin/admins/*') ? 'active submenu' : '' }}">
                        <a data-toggle="collapse" href="#admins">
                            <i class="fas fa-tasks"></i>
                            <p>Role Management</p>
                            <span class="caret"></span>
                        </a>

                        <div class="collapse {{ request()->is('admin/admins') || request()->is('admin/admins/*') || request()->is('admin/roles') || request()->is('admin/roles/*') ? 'show' : '' }}"
                            id="admins">
                            <ul class="nav nav-collapse">

                                <li
                                    class="{{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                    <a href="{{ route('roles.index') }}">
                                        <span class="sub-item">List of roles</span>
                                    </a>
                                </li>

                                <li
                                    class="{{ request()->is('admin/admins') || request()->is('admin/admins/*') ? 'active' : '' }}">
                                    <a href="{{ route('admins.index') }}">
                                        <span class="sub-item">List of Backend users</span>
                                    </a>
                                </li>



                            </ul>
                        </div>
                    </li>
                @endif
                {{-- template management --}}
                @if ($role_permissions == -1 || in_array('TemplatesController', $role_permissions))
                    <li
                        class="nav-item {{ request()->is('admin/templates') || request()->is('admin/templates/*') ? 'active submenu' : '' }}">
                        <a data-toggle="collapse" href="#templates">
                            <i class="fas fa-envelope"></i>
                            <p>Templates Management</p>
                            <span class="caret"></span>
                        </a>

                        <div class="collapse {{ request()->is('admin/templates') || request()->is('admin/templates/*') ? 'show' : '' }}"
                            id="templates">
                            <ul class="nav nav-collapse">

                                <li
                                    class="{{ request()->is('admin/templates') || request()->is('admin/templates/*') ? 'active' : '' }}">
                                    <a href="{{ route('templates.index') }}">
                                        <span class="sub-item">List of Templates</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                @endif
                {{-- cms management --}}
                @if ($role_permissions == -1 || in_array('CmsController', $role_permissions))
                    <li
                        class="nav-item {{ request()->is('admin/pages') || request()->is('admin/pages/*') ? 'active submenu' : '' }}">
                        <a data-toggle="collapse" href="#cms">
                            <i class="fas fa-file-alt"></i>
                            <p>CMS Management</p>
                            <span class="caret"></span>
                        </a>

                        <div class="collapse {{ request()->is('admin/pages') || request()->is('admin/pages/*') ? 'show' : '' }}"
                            id="cms">
                            <ul class="nav nav-collapse">
                                <li
                                    class="{{ request()->is('admin/pages') || request()->is('admin/pages/*') ? 'active' : '' }}">
                                    <a href="{{ route('pages.index') }}">
                                        <span class="sub-item">List of Pages</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                @endif
                <!-- setting management -->
                @if ($role_permissions == -1 || in_array('SettingController', $role_permissions))

                    <li
                        class="nav-item {{ request()->is('admin/settings') || request()->is('admin/settings/*') ? 'active submenu' : '' }}">
                        <a data-toggle="collapse" href="#setting">
                            <i class="fas fa-cog"></i>
                            <p>Setting Management</p>
                            <span class="caret"></span>
                        </a>

                        <div class="collapse {{ request()->is('admin/settings') || request()->is('admin/settings/*') ? 'show' : '' }}"
                            id="setting">
                            <ul class="nav nav-collapse">

                                <li class="{{ request()->is('admin/settings/*') ? 'active' : '' }}">
                                    <a href="{{ route('settings.index') }}">
                                        <span class="sub-item">Site Setting</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</div>